In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('INvideos.csv')
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12T12:20:39.000Z,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12T15:48:08.000Z,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
2,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12T07:08:48.000Z,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
3,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13T01:14:16.000Z,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...
4,il_pSa5l98w,17.14.11,"MCA (Middle Class Abbayi) TEASER - Nani,Sai Pa...",Dil Raju,24,2017-11-10T04:29:50.000Z,"Nenu Local|""Nenu Local Telugu Movie""|""Nani""|""S...",6106669,98612,4185,4763,https://i.ytimg.com/vi/il_pSa5l98w/default.jpg,False,False,False,Watch MCA- Middle Class Abbayi First Look Teas...

In [3]:
df.drop(['tags','thumbnail_link','description'],axis=1,inplace=True)

In [4]:
df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12T12:20:39.000Z,1096327,33966,798,882,False,False,False
1,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12T15:48:08.000Z,473988,2011,243,149,False,False,False
2,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12T07:08:48.000Z,1242680,70353,1624,2684,False,False,False
3,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13T01:14:16.000Z,464015,492,293,66,False,False,False
4,il_pSa5l98w,17.14.11,"MCA (Middle Class Abbayi) TEASER - Nani,Sai Pa...",Dil Raju,24,2017-11-10T04:29:50.000Z,6106669,98612,4185,4763,False,False,False

In [5]:
#df.info()

In [6]:
df['trending_date']=pd.to_datetime(df['trending_date'],format='%y.%d.%m')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37351 entries, 0 to 37350
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                37351 non-null  object
 1   trending_date           37351 non-null  datetime64[ns]
 2   title                   37351 non-null  object
 3   channel_title           37351 non-null  object
 4   category_id             37351 non-null  int64
 5   publish_time            37351 non-null  object
 6   views                   37351 non-null  int64
 7   likes                   37351 non-null  int64
 8   dislikes                37351 non-null  int64
 9   comment_count           37351 non-null  int64
 10  comments_disabled       37351 non-null  bool
 11  ratings_disabled        37351 non-null  bool
 12  video_error_or_removed  37351 non-null  bool
dtypes: bool(3), datetime64[ns](1), int64(5), object(4)
memory usage: 3.0+ MB

In [8]:
df.video_id.value_counts()

#NAME?         511
rRr1qiJRsXk     16
1J76wN0TPI4     14
l7E0kTvARsA     14
WDiK14qI3pQ     13
              ...
Txd2-qx2pjg      1
0euwv8NR5Bk      1
xjFKfAudCOo      1
6Xl5QzRQx4I      1
3JuZ0ksTYSM      1
Name: video_id, Length: 16307, dtype: int64

In [9]:
df = df.drop_duplicates(subset=['video_id'],keep='last')

In [10]:
df.video_id.value_counts()

ePT5gvwiQV0    1
eMJuMB1asf8    1
vpNnkd8CkSs    1
ywruD49dUzE    1
s5Svk84Nc_I    1
              ..
rX1qck58UVs    1
fDaBaRMGqqc    1
NrdO7yczTQM    1
uC_jUDyWAmc    1
3JuZ0ksTYSM    1
Name: video_id, Length: 16307, dtype: int64

In [11]:
df.publish_time.head()

11    2017-11-13T09:51:59.000Z
21    2017-11-13T15:00:01.000Z
23    2017-11-13T06:03:49.000Z
24    2017-11-12T09:45:58.000Z
30    2017-11-11T07:49:46.000Z
Name: publish_time, dtype: object

In [13]:
#df['month'] = df['publish_time'].dt.month